spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}.startupservice.svc.cluster.local:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  management:
    endpoints:
      web:
        exposure:
          include: health # health 엔드포인트를 노출
    health:
      livenessstate:
        enabled: true    # Liveness 상태를 활성화
      readinessstate:
        enabled: true    # Readiness 상태를 활성화
  elasticsearch:
    uris: http://elasticsearch:9200
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb.startupservice.svc.cluster.local:27017/news_database?authSource=admin

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false