spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    # MongoDB 설정 추가
  data:
    mongodb:
      uri: mongodb://localhost:27017/news_database  # MongoDB URI


  elasticsearch:
    rest:
      uris: http://localhost:9200

server:
  port: 8080