CREATE SEQUENCE IF NOT EXISTS startup_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 1;


CREATE SEQUENCE IF NOT EXISTS ssi_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 1;
